# version: "3.8"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    environment:
      CLIENT_MAX_BODY_SIZE: 10m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
    networks:
      - app_network

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
    networks:
      - app_network

  #! Database service
  database:
    image: mysql:8.0.32
    container_name: database
    platform: linux/amd64
    restart: always
    environment:
      DATABASE_URL: mysql://root:R@MIN3517r@m@localhost:3306/parallane
      MYSQL_DATABASE: parallane
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app_network

  #! Tutor service
  tutor:
    build:
      context: .
      dockerfile: ./apps/tutor/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
    container_name: tutor
    restart: always
    env_file:
      - /root/projects/parallane/apps/tutor/.env.local
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: tutor.parallane.com
      LETSENCRYPT_HOST: tutor.parallane.com
      LETSENCRYPT_EMAIL: admin@parallane.com
      DATABASE_URL: "mysql://root@database:3306/parallane"
      NEXTAUTH_URL: https://tutor.parallane.com
      CLIENT_MAX_BODY_SIZE: 10m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - db_backups:/app/backups

  #! Admin service
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
    container_name: admin
    restart: always
    env_file:
      - /root/projects/parallane/apps/admin/.env.local
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: admin.parallane.com
      LETSENCRYPT_HOST: admin.parallane.com
      LETSENCRYPT_EMAIL: admin@parallane.com
      NEXTAUTH_URL: https://admin.parallane.com
      CLIENT_MAX_BODY_SIZE: 10m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - db_backups:/app/backups
      - /root/projects/parallane/apps/admin/ga.json:/app/ga.json:ro # Google Analytics

  #! App service
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
    container_name: app
    restart: always
    env_file:
      - /root/projects/parallane/apps/app/.env.local
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: parallane.com
      LETSENCRYPT_HOST: parallane.com
      LETSENCRYPT_EMAIL: admin@parallane.com
      NEXTAUTH_URL: https://parallane.com
      CLIENT_MAX_BODY_SIZE: 10m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - db_backups:/app/backups

volumes:
  database:
  certs:
  vhost.d:
  html:
  db_backups:

networks:
  app_network:
    external: true
